# Convolutional Nueral Network(CNN) : Convolution, ReLu, Maxpooling and Flattening layers.

In [235]:
horz_edge_array = np.array([[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
              [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
              [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
              [1,1,1,1,1,1,1,1,1,1,200,1,1,1,1,1,1,1,1,1],
              [1,1,1,1,1,1,1,1,1,200,200,1,1,1,1,1,1,1,1,1],
              [1,1,1,1,1,1,1,1,200,200,200,1,1,1,1,1,1,1,1,1],
              [1,1,1,1,1,1,1,200,200,200,200,1,1,1,1,1,1,1,1,1],
              [1,1,1,1,1,1,1,1,1,200,200,1,1,1,1,1,1,1,1,1],
              [1,1,1,1,1,1,1,1,1,200,200,1,1,1,1,1,1,1,1,1],
              [1,1,1,1,1,1,1,1,1,200,200,1,1,1,1,1,1,1,1,1],
               [1,1,1,1,1,1,1,1,1,200,200,1,1,1,1,1,1,1,1,1],
               [1,1,1,1,1,1,1,1,1,200,200,1,1,1,1,1,1,1,1,1],
               [1,1,1,1,1,1,1,1,1,200,200,1,1,1,1,1,1,1,1,1],
               [1,1,1,1,1,1,1,1,1,200,200,1,1,1,1,1,1,1,1,1],
               [1,1,1,1,1,1,1,1,1,200,200,1,1,1,1,1,1,1,1,1],
               [1,1,1,1,1,1,1,1,1,200,200,1,1,1,1,1,1,1,1,1],
               [1,1,1,1,1,1,1,1,1,200,200,1,1,1,1,1,1,1,1,1],
               [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
               [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
               [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]])


print('Original image with horizontal edge.\n')
print(horz_edge_array)


Original image with horizontal edge.

[[  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
    1   1]
 [  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
    1   1]
 [  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
    1   1]
 [  1   1   1   1   1   1   1   1   1   1 200   1   1   1   1   1   1   1
    1   1]
 [  1   1   1   1   1   1   1   1   1 200 200   1   1   1   1   1   1   1
    1   1]
 [  1   1   1   1   1   1   1   1 200 200 200   1   1   1   1   1   1   1
    1   1]
 [  1   1   1   1   1   1   1 200 200 200 200   1   1   1   1   1   1   1
    1   1]
 [  1   1   1   1   1   1   1   1   1 200 200   1   1   1   1   1   1   1
    1   1]
 [  1   1   1   1   1   1   1   1   1 200 200   1   1   1   1   1   1   1
    1   1]
 [  1   1   1   1   1   1   1   1   1 200 200   1   1   1   1   1   1   1
    1   1]
 [  1   1   1   1   1   1   1   1   1 200 200   1   1   1   1   1   1   1
    1   1]
 [  1   1   1   1   1   1  

In [236]:
conv_mat_horiz = np.zeros([20, 20], dtype = int)

sobel_horiz_edge_fil = np.array([[-1,0, 1],[-2,0, 2],[-1,0,1]])
print('The sobel horizontal edge filter\n')
print(sobel_horiz_edge_fil)

The sobel horizontal edge filter

[[-1  0  1]
 [-2  0  2]
 [-1  0  1]]


In [237]:
rows = horz_edge_array.shape[0]
cols = horz_edge_array.shape[1]


for i in range(1,rows-1):
    for j in range(1,cols-1):
        #conv_mat[i][j]=A[i-1][j-1]*sobel_vert_edge_fil[0][0]+ A[i-1][j]*sobel_vert_edge_fil[0][1]+ A[i-1][j+1]*sobel_vert_edge_fil[0][2]+A[i][j-1]*sobel_vert_edge_fil[1][0]+ A[i][j]*sobel_vert_edge_fil[1][1] + A[i][j+1]*sobel_vert_edge_fil[1][2]+A[i+1][j-1]*sobel_vert_edge_fil[2][0]+ A[i+1][j]*sobel_vert_edge_fil[2][1] + A[i+1][j+1]*sobel_vert_edge_fil[2][2]
        conv_mat_horiz[i][j]=horz_edge_array[i-1][j-1]*sobel_horiz_edge_fil[0][0]+ horz_edge_array[i-1][j]*sobel_horiz_edge_fil[0][1]+ horz_edge_array[i-1][j+1]*sobel_horiz_edge_fil[0][2]+horz_edge_array[i][j-1]*sobel_horiz_edge_fil[1][0]+ horz_edge_array[i][j]*sobel_horiz_edge_fil[1][1] + horz_edge_array[i][j+1]*sobel_horiz_edge_fil[1][2]+horz_edge_array[i+1][j-1]*sobel_horiz_edge_fil[2][0]+ horz_edge_array[i+1][j]*sobel_horiz_edge_fil[2][1] + horz_edge_array[i+1][j+1]*sobel_horiz_edge_fil[2][2]

print('Convolved array with edge filter.\n')
print(conv_mat_horiz)

Convolved array with edge filter.

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0  199    0 -199    0    0
     0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0  199  597 -199 -597    0    0
     0    0    0    0    0    0]
 [   0    0    0    0    0    0    0  199  597  597 -597 -796    0    0
     0    0    0    0    0    0]
 [   0    0    0    0    0    0  199  597  597  199 -796 -796    0    0
     0    0    0    0    0    0]
 [   0    0    0    0    0    0  398  597  398  199 -796 -796    0    0
     0    0    0    0    0    0]
 [   0    0    0    0    0    0  199  199  597  597 -796 -796    0    0
     0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0  796  796 -796 -796    0    0
     0    0    0    0    0    0]
 [   0    0    0    

# ReLu on the convolved array.(Convert all negative elements 0)

In [238]:
relu_mat=np.maximum(conv_mat_horiz, 0)

print('The output of the  Rectified Linear unit(ReLu)')
relu_mat


The output of the  Rectified Linear unit(ReLu)


array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 199,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 199, 597,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 199, 597, 597,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0, 199, 597, 597, 199,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0, 398, 597, 398, 199,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0, 199, 199, 597, 597,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 796, 796,   0,  

# Max pooling

In [239]:
M, N = relu_mat.shape
K = 2
L = 2

MK = M // K
NL = N // L

max_pooled_mat= relu_mat[:MK * K, :NL * L].reshape(MK, K, NL, L).max(axis=(1, 3))

print('The output of the Max Pooling on ReLu output array')
max_pooled_mat


The output of the Max Pooling on ReLu output array


array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 597,   0,   0,   0,   0,   0],
       [  0,   0,   0, 597, 597,   0,   0,   0,   0,   0],
       [  0,   0,   0, 597, 597,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 796,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 796,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 796,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 796,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 597,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

# Flattening of the the feature map

In [240]:
rows,columns=max_pooled_mat.shape
siz=rows*columns
CNN_one_layer=max_pooled_mat.reshape(1,siz)

print('The output of the flattening layer')
CNN_one_layer

The output of the flattening layer


array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 597,   0,   0,   0,   0,   0,   0,   0,   0, 597, 597,   0,
          0,   0,   0,   0,   0,   0,   0, 597, 597,   0,   0,   0,   0,
          0,   0,   0,   0,   0, 796,   0,   0,   0,   0,   0,   0,   0,
          0,   0, 796,   0,   0,   0,   0,   0,   0,   0,   0,   0, 796,
          0,   0,   0,   0,   0,   0,   0,   0,   0, 796,   0,   0,   0,
          0,   0,   0,   0,   0,   0, 597,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0]])